# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1357747f275626a99ed1c6311e6da01e0ce4ecfe5df20e0f429d76f114fcffa4a3e10acfa32ee5c4e3f5887f8be69cb34b3e8a84d4ec3eef9f064194b4af259e

test:
  secret_key_base: af403ea867b3d4a64ceb78fb31e6faf27f09786ce6f1de194fabf8a7a77f9c4dfe59e881d430e1141cec00173bd25ec52c4f6ab080150d5258af7ff209bacdfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
